# A list of target clusters for which link resources will be deployed
clusterLinks: []
  # - name: workload-cluster-1
  #   gatewayAddress: 35.219.192.3
  #   gatewayIdentity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
  #   secretName: cluster-credentials-workload-cluster-1
  #   linkAnnotations:
  #     buoyant.cloud/target-cluster: workload-1
  #   serviceAccountAnnotations:
  #     iam.gke.io/gcp-service-account: linkerd-multicluster@my-gcp-project.iam.gserviceaccount.com
  #   targetClusterDomain: cluster.local
  #   targetClusterLinkerdNamespace: linkerd

# Label key and value for Services in target clusters that should be mirrored to source cluster
mirroredServiceLabel:
  key: mirror.linkerd.io/exported
  value: "true"

# Version of Linkerd Service Mirror image
linkerdVersion: stable-2.12.4
